In [1]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [35]:
driver = webdriver.Chrome()

In [20]:
driver.get("https://www.youtube.com/results?search_query=travel")

In [14]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
    links.append(i.get_attribute('href'))
print(len(links))


630


In [15]:
df_travel = pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [21]:
wait = WebDriverWait(driver, 10)
v_category = "Travel"
for x in links:
    if x!=None:
        driver.get(x)
        v_id = x.strip('https://www.youtube.com/watch?v=')
        v_title = wait.until(EC.presence_of_element_located(
            (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
        v_description = wait.until(EC.presence_of_element_located(
            (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
        df_travel.loc[len(df_travel)] = [v_id, v_title, v_description, v_category]

In [29]:
df_travel.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\travel.csv',index=False,header=True)

In [34]:
pd.read_csv("travel.csv").head()


link title                                        description  \
0      JLZlCZ0   NaN  The journey to Arunachal, North East India beg...   
1   CWqFw9kmCn   NaN  Millennials simply quit their jobs to travel. ...   
2  ODuEl4oNae0   NaN  Do you know what the least visited country in ...   
3   Qmi-Xwq-ME   NaN  We are selecting one person who makes a purcha...   
4  _ch7hYh4BtA   NaN  Exploring more of Somalia and travelling to th...   

  category  
0   Travel  
1   Travel  
2   Travel  
3   Travel  
4   Travel

In [131]:
driver.get("https://www.youtube.com/results?search_query=science")

In [136]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
            links.append(i.get_attribute('href'))

print(len(links))

536


In [137]:
df_science = pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [138]:
wait = WebDriverWait(driver, 10)
v_category = "Science"
for x in links:
    if x!=None:
            driver.get(x)
            v_id = x.strip('https://www.youtube.com/watch?v=')
            v_title = wait.until(EC.presence_of_element_located(
                           (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
            v_description =  wait.until(EC.presence_of_element_located(
                                         (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
            df_science.loc[len(df_science)] = [v_id, v_title, v_description, v_category]

In [139]:
df_science.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\science.csv',index=False,header=True)

In [140]:
pd.read_csv("science.csv").head()

link                                              title  \
0      KZbEG3U     The Science of Sound || ध्वनि का रहस्य/विज्ञान   
1  VoLZXXQL-YY  9 Incredible Science Facts You Probably Didn't...   
2    Q6xRG2NCE  🔴LIVE: Blaze's Science Ideas Save the Day! | B...   
3  -kHfA2iy6UQ                                                NaN   
4   U8X-fd_zQQ  12 Cool Science Tricks That Will Make Your Fri...   

                                         description category  
0  Hi Guys Welcome To Question World\nWe All Want...  Science  
1  Common scientific facts you won't believe are ...  Science  
2  Blaze is one of Axle City's greatest problem s...  Science  
3  Cell Structure and Function L2 | NCERT Class 8...  Science  
4  Impress your friends this weekend with these 1...  Science

In [52]:
driver.get("https://www.youtube.com/results?search_query=food")

In [56]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
            links.append(i.get_attribute('href'))

print(len(links))

500


In [57]:
df_food = pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [58]:
wait = WebDriverWait(driver, 10)
v_category = "Food"
for x in links:
    if x!=None:
            driver.get(x)
            v_id = x.strip('https://www.youtube.com/watch?v=')
            v_title = wait.until(EC.presence_of_element_located(
                           (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
            v_description =  wait.until(EC.presence_of_element_located(
                                         (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
            df_food.loc[len(df_food)] = [v_id, v_title, v_description, v_category]

In [118]:
df_food.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\food.csv',index=False,header=True)

In [119]:
pd.read_csv("food.csv").head()

link                                              title  \
0  0SPwwpruGIA                                                NaN   
1       X6-iv7  CRAZY FOOD HACKS || Unusual Recipes That Will ...   
2   BBj2oeJWW4  Egyptian Street Food - Seafood HEAVEN + Tradit...   
3   LAsnbgOoGz                                                NaN   
4  LHr1na5DZ44  101 Indian Street Food Dishes to Eat Before Yo...   

                                         description category  
0  This is the ultimate must-try food bucket list...     Food  
1  TIMESTAMPS:\n00:04 DIY Giant food\n01:14 Giant...     Food  
2  Check out https://ExpressVPN.com/thefoodranger...     Food  
3  Download BalleBaazi app \nManage by -: AdMart....     Food  
4  🧳 101 Indian Street Food Dishes Kindle Book: h...     Food

In [63]:
driver.get("https://www.youtube.com/results?search_query=history")

In [68]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
            links.append(i.get_attribute('href'))

print(len(links))

533


In [69]:
df_history = pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [70]:
wait = WebDriverWait(driver, 10)
v_category = "history"
for x in links:
    if x!=None:
            driver.get(x)
            v_id = x.strip('https://www.youtube.com/watch?v=')
            v_title = wait.until(EC.presence_of_element_located(
                           (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
            v_description =  wait.until(EC.presence_of_element_located(
                                         (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
            df_history.loc[len(df_history)] = [v_id, v_title, v_description, v_category]

In [124]:
df_history.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\history.csv',index=False,header=True)

In [125]:
pd.read_csv("history.csv").head()

link                                              title  \
0    jmp8CoZBI                                                NaN   
1  3DQC3S3bJc0  The Mayflower: 400th Anniversary Special | His...   
2   6vaWug73kD               10 Biggest Lies Ever Told In History   
3   R1Pmcy74Kf        One Direction - History (Official 4K Video)   
4  WltJPKFo_J4                                                NaN   

                                         description category  
0  One Direction – History (Official Video)\nFoll...  history  
1  In today's special episode of History Hit Live...  history  
2  History is written by the victor - is very tru...  history  
3  One Direction – History (Official Video)\nFoll...  history  
4  This is the first part of The History of the W...  history

In [75]:
driver.get("https://www.youtube.com/results?search_query=manufacturing")

In [77]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
            links.append(i.get_attribute('href'))

print(len(links))

562


In [78]:
df_manufacturing= pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [79]:
wait = WebDriverWait(driver, 10)
v_category = "manufacturing"
for x in links:
    if x!=None:
            driver.get(x)
            v_id = x.strip('https://www.youtube.com/watch?v=')
            v_title = wait.until(EC.presence_of_element_located(
                           (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
            v_description =  wait.until(EC.presence_of_element_located(
                                         (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
            df_manufacturing.loc[len(df_manufacturing)] = [v_id, v_title, v_description, v_category]

In [127]:
df_manufacturing.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\manufacturing.csv',
                        index=False,header=True)

In [128]:
pd.read_csv("manufacturing.csv").head()

link                                              title  \
0  XyP_7IZzpeI                                                NaN   
1  Y8GT6Wv9mQE  Most Interesting Manufacturing Processes That ...   
2  xAv4qKrKvII  Awesome Manufacturing and Processing Methods N...   
3   SFomXXXYMX  Amazing Plywood Manufacturing Process ! Extrem...   
4   xh8LdkoAcQ  Most amazing modern manufacturing process tech...   

                                         description       category  
0  Modern Continuous Manufacturing Processes For ...  manufacturing  
1  Amazing Manufacturing Processes Everyone Shoul...  manufacturing  
2  Awesome Manufacturing and Processing Methods N...  manufacturing  
3  Woodart is a channel that show all Woodworks:\...  manufacturing  
4  Most amazing modern manufacturing process tech...  manufacturing

In [85]:
driver.get("https://www.youtube.com/results?search_query=art_dance")

In [88]:
user_data = driver.find_elements_by_xpath('//*[@id="video-title"]')
links = []
for i in user_data:
            links.append(i.get_attribute('href'))

print(len(links))

503


In [89]:
df_artndance = pd.DataFrame(columns = ['link', 'title', 'description', 'category'])

In [90]:
wait = WebDriverWait(driver, 10)
v_category = "artndance"
for x in links[:420]:
    if x!=None:
            driver.get(x)
            v_id = x.strip('https://www.youtube.com/watch?v=')
            v_title = wait.until(EC.presence_of_element_located(
                           (By.CSS_SELECTOR,"h1.title yt-formatted-string"))).text
            v_description =  wait.until(EC.presence_of_element_located(
                                         (By.CSS_SELECTOR,"div#description yt-formatted-string"))).text
            df_artndance.loc[len(df_artndance)] = [v_id, v_title, v_description, v_category]

In [129]:
df_artndance.to_csv(r'C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\artndance.csv',index=False,header=True)

In [130]:
pd.read_csv("artndance.csv").head()

link                                              title  \
0  1UV3zen3lv4                                                NaN   
1   ff-y0G205J  NO TE SOLTARE - Yandel, Nicky Jam- Zumba - Reg...   
2  l0-INrfxD1Y  WARM UP - Zumba® - ShowMan Pitbull l Choreogra...   
3  RkNDsETIU5U                     VIBE ART DANCE STUDIO - Faraon   
4   qRVsL1ZP1Y  WARM UP 2018 - Zumba® - Dj Baddmixx - Coreogra...   

                                         description   category  
0  #toma #luisasonza #mczaac\nTOMA - Luísa Sonza,...  artndance  
1  NO TE SOLTARE - Yandel, Nicky Jam- Zumba - Reg...  artndance  
2  WARM UP - Zumba® - ShowMan Pitbull l Choreogra...  artndance  
3  Gurinel TV - Prima televiziune a copiilor din ...  artndance  
4  WARM UP 2018 -  Zumba® - Dj Baddmixx - Coreogr...  artndance

In [110]:
import numpy as np

In [141]:
df_travel = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\travel.csv")
df_travel['title'] = df_travel['title'].replace(np.nan,'travel')
print(len(df_travel))
df_travel.head()

658


link   title                                        description  \
0      JLZlCZ0  travel  The journey to Arunachal, North East India beg...   
1   CWqFw9kmCn  travel  Millennials simply quit their jobs to travel. ...   
2  ODuEl4oNae0  travel  Do you know what the least visited country in ...   
3   Qmi-Xwq-ME  travel  We are selecting one person who makes a purcha...   
4  _ch7hYh4BtA  travel  Exploring more of Somalia and travelling to th...   

  category  
0   Travel  
1   Travel  
2   Travel  
3   Travel  
4   Travel

In [142]:
df_science = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\science.csv")
df_science['title'] = df_science['title'].replace(np.nan,'science')
print(len(df_science))
df_science.head()

521


link                                              title  \
0      KZbEG3U     The Science of Sound || ध्वनि का रहस्य/विज्ञान   
1  VoLZXXQL-YY  9 Incredible Science Facts You Probably Didn't...   
2    Q6xRG2NCE  🔴LIVE: Blaze's Science Ideas Save the Day! | B...   
3  -kHfA2iy6UQ                                            science   
4   U8X-fd_zQQ  12 Cool Science Tricks That Will Make Your Fri...   

                                         description category  
0  Hi Guys Welcome To Question World\nWe All Want...  Science  
1  Common scientific facts you won't believe are ...  Science  
2  Blaze is one of Axle City's greatest problem s...  Science  
3  Cell Structure and Function L2 | NCERT Class 8...  Science  
4  Impress your friends this weekend with these 1...  Science

In [143]:
df_history = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\history.csv")
df_history['title'] = df_history['title'].replace(np.nan,'history')
print(len(df_history))
df_history.head()

509


link                                              title  \
0    jmp8CoZBI                                            history   
1  3DQC3S3bJc0  The Mayflower: 400th Anniversary Special | His...   
2   6vaWug73kD               10 Biggest Lies Ever Told In History   
3   R1Pmcy74Kf        One Direction - History (Official 4K Video)   
4  WltJPKFo_J4                                            history   

                                         description category  
0  One Direction – History (Official Video)\nFoll...  history  
1  In today's special episode of History Hit Live...  history  
2  History is written by the victor - is very tru...  history  
3  One Direction – History (Official Video)\nFoll...  history  
4  This is the first part of The History of the W...  history

In [144]:
df_food = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\food.csv")
df_food['title'] = df_food['title'].replace(np.nan,'food')
print(len(df_food))
df_food.head()

500


link                                              title  \
0  0SPwwpruGIA                                               food   
1       X6-iv7  CRAZY FOOD HACKS || Unusual Recipes That Will ...   
2   BBj2oeJWW4  Egyptian Street Food - Seafood HEAVEN + Tradit...   
3   LAsnbgOoGz                                               food   
4  LHr1na5DZ44  101 Indian Street Food Dishes to Eat Before Yo...   

                                         description category  
0  This is the ultimate must-try food bucket list...     Food  
1  TIMESTAMPS:\n00:04 DIY Giant food\n01:14 Giant...     Food  
2  Check out https://ExpressVPN.com/thefoodranger...     Food  
3  Download BalleBaazi app \nManage by -: AdMart....     Food  
4  🧳 101 Indian Street Food Dishes Kindle Book: h...     Food

In [145]:
df_manufacturing = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\manufacturing.csv")
df_manufacturing['title'] = df_manufacturing['title'].replace(np.nan,'manufacturing')
print(len(df_manufacturing))
df_manufacturing.head()

538


link                                              title  \
0  XyP_7IZzpeI                                      manufacturing   
1  Y8GT6Wv9mQE  Most Interesting Manufacturing Processes That ...   
2  xAv4qKrKvII  Awesome Manufacturing and Processing Methods N...   
3   SFomXXXYMX  Amazing Plywood Manufacturing Process ! Extrem...   
4   xh8LdkoAcQ  Most amazing modern manufacturing process tech...   

                                         description       category  
0  Modern Continuous Manufacturing Processes For ...  manufacturing  
1  Amazing Manufacturing Processes Everyone Shoul...  manufacturing  
2  Awesome Manufacturing and Processing Methods N...  manufacturing  
3  Woodart is a channel that show all Woodworks:\...  manufacturing  
4  Most amazing modern manufacturing process tech...  manufacturing

In [146]:
df_artndance = pd.read_csv(r"C:\Users\Devanand\Desktop\Refactored_Py_DS_ML_Bootcamp-master\artndance.csv")
df_artndance['title'] = df_artndance['title'].replace(np.nan,'artndance')
print(len(df_artndance))
df_artndance.head()

414


link                                              title  \
0  1UV3zen3lv4                                          artndance   
1   ff-y0G205J  NO TE SOLTARE - Yandel, Nicky Jam- Zumba - Reg...   
2  l0-INrfxD1Y  WARM UP - Zumba® - ShowMan Pitbull l Choreogra...   
3  RkNDsETIU5U                     VIBE ART DANCE STUDIO - Faraon   
4   qRVsL1ZP1Y  WARM UP 2018 - Zumba® - Dj Baddmixx - Coreogra...   

                                         description   category  
0  #toma #luisasonza #mczaac\nTOMA - Luísa Sonza,...  artndance  
1  NO TE SOLTARE - Yandel, Nicky Jam- Zumba - Reg...  artndance  
2  WARM UP - Zumba® - ShowMan Pitbull l Choreogra...  artndance  
3  Gurinel TV - Prima televiziune a copiilor din ...  artndance  
4  WARM UP 2018 -  Zumba® - Dj Baddmixx - Coreogr...  artndance

In [147]:
min_size = min(len(df_travel),len(df_science),len(df_food),len(df_history),len(df_manufacturing),len(df_artndance))

In [148]:
min_size

414

In [151]:
frames = [df_travel[:min_size], df_science[:min_size], df_food[:min_size], df_history[:min_size],
          df_manufacturing[:min_size], df_artndance[:min_size]]
df_copy = pd.concat(frames, axis=0, join='outer', ignore_index=True,
                            keys=None, levels=None, names=None, verify_integrity=False, copy=True)

In [152]:
len(df_copy)

2484

In [153]:
df_link = pd.DataFrame(columns = ["link"])        
df_title = pd.DataFrame(columns = ["title"])        
df_description = pd.DataFrame(columns = ["description"])        
df_category = pd.DataFrame(columns = ["category"])        
df_link['link'] = df_copy['link'] 
df_title ['title']= df_copy['title'] 
df_description['description'] = df_copy['description'] 
df_category['category'] = df_copy['category']

In [154]:
import re 
import nltk 
nltk.download('stopwords') 
from nltk.corpus import stopwords 
from nltk.stem.porter import PorterStemmer


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Devanand\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [155]:
len(df_title)

2484

In [156]:
corpus = []        
for i in range(0, len(df_title)):
    if type(df_title['title'][i])==str :
      review = re.sub("[^a-zA-Z]",' ', df_title['title'][i])            
      review = review.lower()            
      review = review.split()            
      ps = PorterStemmer()            
      review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]            
      review = ' '.join(review)            
      corpus.append(review)

In [160]:
print(len(corpus))
corpus[:20]

2484


['travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel',
 'travel least visit countri world']

In [161]:
len(df_description)

2484

In [162]:
corpus1 = [] 
for i in range(0, len(df_description)):        
    if type(df_description['description'][i])==str:
      review = re.sub('[^a-zA-Z]', ' ', df_description['description'][i])            
      review = review.lower()            
      review = review.split()            
      ps = PorterStemmer()            
      review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]            
      review = ' '.join(review)            
      corpus1.append(review)

In [163]:
corpus1[:1]


['journey arunach north east india begin train journey guwahati murkongselek head pasighat travel companion get start explor tini glimps arunach far market bridg adventur get better next video']

In [164]:
dftitle = pd.DataFrame({'title':corpus})
dfdescription = pd.DataFrame({'description':corpus1})

In [165]:
set(df_category['category'])

{'Food', 'Science', 'Travel', 'artndance', 'history', 'manufacturing'}

In [166]:
from sklearn.preprocessing import LabelEncoder
dfcategory = df_category.apply(LabelEncoder().fit_transform)
dfcategory

category
0            2
1            2
2            2
3            2
4            2
...        ...
2479         3
2480         3
2481         3
2482         3
2483         3

[2484 rows x 1 columns]

In [183]:
df_new = pd.concat([df_link, dftitle, dfdescription, dfcategory], axis=1)
df_new

link                                              title  \
0         JLZlCZ0                                             travel   
1      CWqFw9kmCn                                             travel   
2     ODuEl4oNae0                                             travel   
3      Qmi-Xwq-ME                                             travel   
4     _ch7hYh4BtA                                             travel   
...           ...                                                ...   
2479  qpheb6uWkYM  drupadi mila art danc gyeongju world cultur fe...   
2480    nGaDQsQeF  eto ta jabroso megamix salsa choke coreografia...   
2481    LhSo_1r_G  dura daddi yanke coreografia l cia art danc l ...   
2482  0w3ksavmveU             temur tsnobiladz tiko chitidz art danc   
2483   85eo8cB1Kg      rabiola mc kevinho coreografia l cia art danc   

                                            description  category  
0     journey arunach north east india begin train j...         2  
1     millenni simpli quit job travel gener insati w...         2  
2     know least visit countri world experi incred s...         2  
3     select one person make purchas seek discomfort...         2  
4     explor somalia travel coast instagram photo so...         2  
...                                                 ...       ...  
2479                                                NaN         3  
2480                                                NaN         3  
2481                                                NaN         3  
2482                                                NaN         3  
2483                                                NaN         3  

[2484 rows x 4 columns]

In [223]:
from sklearn.feature_extraction.text import CountVectorizer   
cv = CountVectorizer(max_features=1500) 
X = cv.fit_transform(corpus, corpus1).toarray() 
y = df_new.iloc[:, 3].values

In [244]:
df_zer=X[1000]
df_zer

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [237]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 101)

In [238]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100,criterion = 'entropy',max_features=6)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_features=6)

In [239]:
y_pred = classifier.predict(X_test)
classifier.score(X_test, y_test)

0.9919571045576407

In [240]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       133
           1       0.98      0.99      0.98       122
           2       1.00      0.98      0.99       139
           3       1.00      1.00      1.00       119
           4       0.99      0.99      0.99       118
           5       1.00      0.99      1.00       115

    accuracy                           0.99       746
   macro avg       0.99      0.99      0.99       746
weighted avg       0.99      0.99      0.99       746



In [241]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[133   0   0   0   0   0]
 [  0 121   0   0   1   0]
 [  2   1 136   0   0   0]
 [  0   0   0 119   0   0]
 [  0   1   0   0 117   0]
 [  0   1   0   0   0 114]]


In [245]:
classifier.predict(df_zer.reshape(-1,1500))

array([0])